spring:
  profiles:
    active: vault
  cloud:
    config:
      server:
        vault:
          kvVersion: 2

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  port: 8888
