version: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: config-client-vault-db
    environment:
      # we keep the passwords simple here
      - POSTGRES_PASSWORD=password
      - POSTGRES_ROOT_PASSWORD=password # default username is postgres
    ports:
      - "5432:5432"
    volumes:
      - cloud_security_db_data:/var/lib/postgresql/data
    networks:
      - cloud-security
  vault:
    image: hashicorp/vault:1.14.3
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./logs:/vault/logs
      - ./file:/vault/file
      - ./config:/vault/config
      - ./policies:/vault/policies
    entrypoint: vault server -config=/vault/config/file-storage.hcl
    networks:
      - cloud-security

volumes:
  cloud_security_db_data:

networks:
  cloud-security: