spring:
  config:
    import: "configserver:,vault:"
  application:
    name: config-client-vault
  cloud:
    config:
      uri: http://localhost:8888
      token: ${spring.cloud.vault.token}
    vault:
      kv:
        enabled: true
        application-name: ${spring.application.name}
      # enable dynamic database credentials
      database:
        enabled: true
        role: config_client_vault_all_privileges
      host: localhost
      port: 8200
      scheme: http

      # Token authentication
      #authentication: TOKEN

      # root token
      token: hvs.NWNBgPVg7RNyfuad5Qg4MJdg

      # AppRole authentication
      authentication: APPROLE
      # config-client-vault app-role
      app-role:
        role-id: 1f18ad58-50e9-0b7b-09d2-5f36d1356d6e
        secret-id: 4b61e1dd-2301-a5f8-0f8b-8f0826ccab3b
  datasource:
    url: jdbc:postgresql://localhost:5432/config_client_vault
    # credentials are obtained via Vault
  jpa:
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info

config:
  client:
    vault:
      version: '@project.version@'
      title: '@project.name@'
      description: '@project.description@'
      license-name: '@license.name@'
      license-url: '@license.url@'
      contact:
        name: '@project.organization.name@'
        url: '@project.organization.url@'
        email: dominikschadow@gmail.com